# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFriendshipHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('FriendName', models.CharField(max_length=50)),
                ('FriendshipDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserMutualFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('FriendName', models.CharField(max_length=50)),
                ('MutualFriends', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSelfData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('TotalFriends', models.IntegerField()),
                ('Followers', models.IntegerField()),
                ('JoinDate', models.DateField()),
            ],
        ),
    ]
