# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('FriendName', models.CharField(max_length=50)),
                ('MutualFriends', models.IntegerField()),
                ('FriendshipDate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserFriendshipHistory',
        ),
        migrations.DeleteModel(
            name='UserMutualFriends',
        ),
        migrations.AddField(
            model_name='userselfdata',
            name='UserID',
            field=models.CharField(default='dummy', max_length=50),
            preserve_default=False,
        ),
    ]
